# 如果在命令中没有指定, 则使用默认值
# If not specified in the command, the default
default-seconds: 60

firework-rocket:
  # 烟花发射器的名字
  # The name of firework gun
  name: "&c烟花发射器"
  # 烟花发射器的描述
  # Firework gun lore
  lore:
    - "&e右键&7发射一枚烟花!"

message:
  reload: "&6&l烟花 &8» &a重载完毕"
  set: "&6&l烟花 &8» &a烟花发射点设置成功"
  unset: "&6&l烟花 &8» &a烟花发射点删除成功"
  start: "&6&l烟花 &8» &e烟花盛将持续 &c{0} 秒钟&e!"
  gun: "&6&l烟花 &8» &a烟花发射器添加到你的背包了"
  help: |
    ---------- &6&l烟花 ----------
    &c/firework reload &7- 重载插件文件
    &c/firework start [秒数] &7- 开始烟花盛会
    &c/firework set &7- 设置烟花发射点
    &c/firework unset &7- 删除烟花发射点
    &c/firework gun &7- 获取烟花发射器
  no-permission: "&c你没有权限执行此操作"
  non-player: "&c你不是玩家"

#
# ENGLISH
#
#firework-rocket:
#  # The name of firework gun
#  name: "&cFirework rocket"
#  # Firework gun lore
#  lore:
#    - "&eRight-click &7to fire a firework!"
#
#message:
#  reload: "&6&lFirework &8» &aPlugin reloaded successfully"
#  set: "&6&lFirework &8» &aFirework location added successfully"
#  unset: "&6&lFirework &8» &aFirework location removed successfully"
#  start: "&6&lFirework &8» &eThe fireworks show has started for &c{0} seconds&e!"
#  gun: "&6&lFirework &8» &aFirework gun has been added to your inventory."
#  help: |
#    ---------- &6&lFirework ----------
#    &c/firework reload &7- Reload config.yml and data.yml file
#    &c/firework start [time in seconds] &7- Start firework event
#    &c/firework set &7- Set location for firework rocket
#    &c/firework unset &7- Unset location for firework rocket
#    &c/firework gun &7- Get firework gun
#  no-permission: "&cYou cannot do this."
#  non-player: "&cYou cannot do this."
